const types = {
    //USER
    USER_LOGIN: 'USER_LOGIN',

    //REGISTERED USER
    USER_REGISTRATION: 'USER_REGISTRATION',

    //CREATE CONF CODE
    CREATE_CONF_CODE: 'CREATE_CONF_CODE',

    //SET ERROR MESSAGE
    SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
};

export default types;
